<p><a href="/nl_BE/pagina/producten">Ga naar producten</a></p>

<p><a href="<?php echo $this->url(array(
    'controller' => 'page', 
    'action'=> 'index',            
        array('params' => array(
            'slug'  => 'producten',
            'lang'  => 'nl_BE'))
        ));?>">
        Ga naar producten</a></p>
        
<p><a href="<?php echo $this->url(array('slug' => 'producten', 'lang' => 'nl_BE'), 'page'); ?>">Ga naar producten</a></p>