<!doctype HTML>
<html>
    <head>
        <link href="/css/stylesheet.css" rel="stylesheet">
    </head>
    <body>
        <div id="container">
            <header>
                <h1><?php echo $this->translate('text_header');?></h1>
            </header>
            <nav>
                <!--ul>
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Producten</a></li>
                </ul-->
                <?php echo $this->navigation()->menu(); ?>
            </nav>
            <section>
                <article>
                    <?php echo $this->layout()->content; ?>
                </article>
            </section>
        </div>
    </body>
</html>
